services:
    wh_media.twig.thumb:
        class: WH\MediaBundle\Twig\ThumbExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}
    wh_media.filemanager:
        class: WH\MediaBundle\Services\FileManager
        arguments: ['@service_container']
