services:
    wh_media.twig.thumb:
        class: WH\MediaBundle\Twig\ThumbExtension
        arguments: ["@service_container"]
        tags:
            - {name: twig.extension}
#    wh_media.example:
#        class: WH\MediaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
